Project 2/personal_portfolio/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blogs, name='blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

Project 2/personal_portfolio/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from skills import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project 2/personal_portfolio/blog/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date_created = models.DateField()

    def __str__(self):
        return self.title

Project 2/personal_portfolio/skills/models.py
from django.db import models


# Create your models here.
class Skill(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=150)
    image = models.ImageField(upload_to='skills/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

Project 2/personal_portfolio/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.


def blogs(request):
    blog = Blog.objects.order_by('-date_created')
    return render(request, 'blog/blogs.html', {'blogs': blog})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

Project 2/personal_portfolio/skills/views.py
from django.shortcuts import render
from .models import Skill

# Create your views here.


def index(request):
    skills = Skill.objects.all()
    return render(request, 'skills/index.html', {'skills': skills})

Project 2/personal_portfolio/skills/templates/skills/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'skills/favicon.ico' %}">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="menu">
    <div class="wrap">
        <div class="logo">
            <a href="{% url 'index' %}">
                <img src="{% static 'skills/logo.png' %}" alt="">
            </a>
        </div>
        <ul>
            <li><a href="{% url 'index' %}">Главная</a></li>
            <li><a href="{% url 'blog:blogs' %}">Блог</a></li>
            <li target="_blank"><a href="{% static 'skills/resume.pdf' %}">Резюме</a></li>
        </ul>
    </div>
</div>
<div class="content">
    <div class="wrap">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

Project 2/personal_portfolio/skills/templates/skills/index.html
{% extends 'skills/base.html' %}
{% load static %}

{% block content %}
<h1>Developer portfolio</h1>
<div class="img">
    <img src="{% static 'skills/wc.jpg' %}" alt="">
</div>

<h2>Technology stack</h2>
<div class="block">
    {% for skill in skills %}
    <div class="element">
        <div>
            <img src="{{ skill.image.url }}" alt="">
        </div>
        <div class="text">
            <h2><a href="{{ skill.url }}" target="_blank"> {{ skill.title }}</a></h2>
            <p>{{ skill.description }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}